"""Plain-language explanations for meeting controls and upstream settings."""

HELP_TEXT = {
    "start_meeting": "开始会议：开始监听已选择的音频来源并显示实时字幕。例：确认麦克风或系统声音后点击开始；录音与识别会随本次会议启动。",
    "stop_meeting": "停止会议：结束当前音频监听与识别，并完成本次记录。例：会议结束后点击停止；已保存的历史记录仍保留。",
    "pause": "暂停：暂时停止处理新音频，适合休息或临时不想记录时使用。点击继续后恢复；暂停期间不会生成新字幕。",
    "resume": "继续：从暂停状态恢复音频处理与实时字幕。例：休息结束后点击继续；后续语音会继续追加到本次会议。",
    "settings": "设置：调整音频来源、识别语言、翻译、模型和字幕显示等选项。部分服务或模型选项需要下次启动会议时生效。",
    "tools": "会议工具：打开词库、参会者、AI 助手、记录和诊断等会议辅助功能。打开面板不会自动开始录音。",
    "glossary": "词库：为项目名、人名和专业术语保存标准写法。例：将缩写映射到完整设备名称；识别时用于减少专有词错字。",
    "participants": "参会者：维护本次会议涉及的人员信息，方便整理会议记录。例：填写姓名与所属单位；信息不会自动发送给他人。",
    "export": "导出：把本次会议字幕保存为文本或字幕文件。例：选择 SRT 可用于视频字幕；请先确认本次会议已有内容。",
    "save": "保存：保存当前编辑的设置或内容。修改何时生效取决于具体选项；需要重启服务的项目会在说明中标出。",
    "cancel": "取消：放弃本次尚未应用的更改并关闭窗口。",
    "apply": "应用：确认并应用当前修改。部分模型和服务选项要在下次启动会议时才会生效。",
    "overlay_width": "字幕窗宽度：设置独立字幕窗口的横向尺寸。例：长句显示不全时可增大宽度；调整后立即预览并保存。",
    "overlay_height": "字幕窗高度：设置独立字幕窗口的纵向尺寸。例：需要同时查看更多字幕时可增大高度；调整后立即预览并保存。",
    "overlay_background_color": "字幕窗背景颜色：选择字幕窗底色。例：深色背景适合暗光环境；更改会立即预览，确认后保存。",
    "overlay_background_opacity": "字幕窗背景不透明度：100% 为不透明，数值越小越透明。背景太透看不清时提高百分比；只改变背景，文字仍清晰显示，更改会立即预览。",
    "overlay_font_family": "字幕窗字体：选择字幕文字使用的字体。例：选择本机已安装且支持中文的字体；更改会立即预览。",
    "overlay_font_size": "字幕窗字号：设置字幕文字大小。例：远距离观看时调大字号；更改会立即预览。",
    "overlay_source_color": "原文颜色：设置字幕窗中识别原文的文字颜色。例：选择与背景对比明显的颜色；更改会立即预览。",
    "overlay_translation_color": "译文颜色：设置字幕窗中翻译文字的颜色。例：选与原文不同且易读的颜色；更改会立即预览。",
    "overlay_display_mode": "字幕窗显示内容：选择显示原文、译文或双语。例：只看译文可选“译文”；更改后立即生效。",
    "overlay_show_speaker": "显示说话人：控制字幕窗是否显示已识别的说话人标签。仅当当前字幕有说话人信息时显示。",
    "overlay_show_draft": "显示识别/翻译草稿：控制是否显示尚未确认的实时文字。关闭后只看已确认字幕；更改立即生效。",
    "overlay_locked": "锁定字幕窗位置：开启后禁止拖动字幕窗，防止误移动；再次取消勾选即可拖动。",
    "overlay_always_on_top": "字幕窗置顶：让独立字幕窗显示在其他普通窗口前面。关闭后由系统按常规窗口顺序排列。",
    "overlay_translation_toggle": "实时翻译：请求开启或关闭本次会议的翻译。关闭后识别仍可继续；状态由主程序确认后同步。",
    "overlay_appearance": "字幕外观：调整字幕窗尺寸、背景、透明度、字体、颜色和显示内容。更改会即时预览，取消可恢复原样。",
    "overlay_follow_theme": "跟随软件主题配色：打开后，字幕背景和文字自动使用软件所选的深色、晴空蓝或春意绿；关闭后恢复保存的自选颜色。字体、字号和透明度不变。例如软件换成春意绿，字幕也一起换色，无需再选一次预设。",
    "show_main": "返回主窗口：把会议管理窗口带到前台；当前字幕窗和会议继续保持打开。",
    "lan": "识别语言：告诉听写引擎会议主要使用哪种语言。例：英语会议选“英语”，不确定时可选“自动”（部分实时翻译模式要求手动指定）。保存后下次识别生效。",
    "translation_provider": "翻译服务：选择 NLLB 或 LM Studio 作为实际译文来源。例：LM Studio 需已运行并加载模型；暂停后修改可避免打断本次处理。",
    "translation_mode": "翻译开关：选择生成本地译文或仅保留识别原文。例：只需要听写时选择“仅转写”；运行中翻译可由字幕窗开关控制。",
    "font_size": "主窗口记录区字号：调整主窗口本次字幕列表的文字大小；这与独立字幕窗字号分开设置。独立字幕窗请打开“字幕外观”调整。",
    "save_records": "自动保存会议记录：运行中锁定当前选择；暂停后修改并保存后生效。关闭自动保存仍可使用手动保存。",
    "history": "本次字幕：查看当前会议已经识别的内容；这里的字号只影响主窗口记录区，不改变独立字幕窗外观。",
    "llm_model": "问答/摘要模型：显示 AI 助手当前配置的模型名称。未配置时，问答与摘要不可用；本地 NLLB 语音翻译不依赖此模型。此状态只读取已有设置，不会联网查询或加载模型。",
    "source_mode": "音频来源：选择系统声音、麦克风或同时采集两路音频。例：线上会议选择系统声音；面对面会议选择麦克风。设备在音源设置中选择。",
    "overlay_window": "字幕窗：显示或隐藏独立实时字幕窗口。例：主窗口用于操作、字幕窗放在会议画面旁；隐藏窗口不会停止会议。",
    "lmstudio": "LM Studio 翻译：通过本机 LM Studio 服务生成译文。例：先启动 LM Studio 并加载支持的模型，再在这里选择对应模型。服务地址和模型名称必须匹配；切换后新会议生效。",
    "lm_studio_model": "LM Studio 模型：指定本机 LM Studio 当前加载的翻译模型名称。例：填写服务中显示的模型 ID；名称不匹配时无法请求翻译。",
    "target_language": "翻译目标：选择希望看到的译文语言。例：英语讲话、中文译文。关闭翻译时此项不生效；新设置从后续语音片段开始应用。",
    "backend": "识别引擎：选择把语音转成文字的本地引擎。例：默认 faster-whisper。不同引擎支持的语言、硬件和模型不同；通常下次启动服务时生效。",
    "backend_policy": "流式识别策略：决定实时字幕如何平衡速度与修订准确度。例：LocalAgreement 会等待相邻结果一致再确认。下次启动识别服务生效。",
    "model_size": "Whisper 模型：模型越大通常越准确，也越占内存、启动越慢。例：small 适合多数电脑，large-v3 需要更多资源。下次启动识别服务生效。",
    "model_dir": "本地模型目录：指定已下载模型所在文件夹。例：D:/models/whisper。目录应包含引擎需要的模型文件；下次启动服务生效。",
    "model_path": "模型文件：指定识别引擎使用的模型文件。例：本机已有的 .pt 文件。留空时按模型与缓存设置查找；下次启动服务生效。",
    "translation_backend": "翻译引擎：选择生成译文的方式。例：NLLB 使用本地多语言模型。修改后通常在下次启动服务时生效。",
    "nllb_backend": "NLLB 运行后端：选择本地模型的计算程序。例：ctranslate2 通常更省资源，Transformers 适合兼容场景。下次启动翻译服务生效。",
    "nllb_size": "NLLB 模型大小：选择本地翻译模型规模。例：600M 较省内存，1.3B 通常质量更好但占用更多资源。下次启动翻译服务生效。",
    "diarization": "区分说话人：尝试判断每句话由谁说出。例：多人会议中显示不同说话人标签。需要相应模型，通常下次启动识别服务生效。",
    "diarization_backend": "说话人引擎：选择说话人分段与区分方式。例：Sortformer。可能需要额外模型；下次启动服务生效。",
    "sortformer_max_speakers": "最多说话人数：给说话人识别设置人数上限。例：4 表示最多区分四个人。人数太大会增加计算量；下次服务启动生效。",
    "init_prompt": "识别提示词：给识别引擎一段会议背景或术语，帮助理解专有词。例：项目名、设备名。提示会随识别请求使用。",
    "static_init_prompt": "固定提示词：每次识别都附带的背景文字。例：公司名和常见缩写。过长或无关内容可能降低效果；下次识别生效。",
    "glossary": "词库：为常见人名、项目名或术语提供标准写法。例：把容易听错的设备名称统一成正确拼写。保存后新识别内容使用。",
    "participants": "参会者：记录会议参与人员及其信息，便于整理会议记录。例：添加姓名和所属单位；不会自动识别或联系参会者。",
    "api_token": "服务访问令牌：限制谁可以连接本机听译服务。例：由调用端配置相同令牌。请勿分享给无关人员；下次服务启动生效。",
    "host": "服务监听地址：决定本机服务接受哪些网络连接。例：127.0.0.1 仅本机访问。修改后下次启动服务生效。",
    "port": "服务端口：本机服务使用的网络端口。例：8000。端口需未被其他程序占用；下次启动服务生效。",
    "min_chunk_size": "最小音频块：设置每次送去识别的音频最短时长（秒）。例：0.5 秒响应较快；过小可能增加计算压力。下次启动服务生效。",
    "pause_segmentation_seconds": "停顿断句：讲话停顿达到此时长（秒）后更倾向于结束一句。例：0.8 秒。较短会切得更碎，较长会等待更久。下次启动服务生效。",
    "beams": "解码束数：控制识别时尝试的候选文本数量。数值越大可能提高准确度，也会更慢。例：保持默认值；下次启动服务生效。",
    "log_level": "日志级别：控制服务记录多少运行细节。例：INFO 记录常规信息，DEBUG 适合排查问题。下次启动服务生效。",
    'translate_on_complete': '整段完成后翻译：选择等一句话识别完整后再翻译。例：需要完整句子再出译文时开启；默认关闭时采用当前流式翻译设置。仅对已启用且支持的翻译后端有影响。',
    'punctuation_split': '旧版句尾标点切分开关：原库已标记为弃用且不生效。保持默认即可；句子边界由说话人变化和停顿断句设置处理。',
    'disable_punctuation_split': '旧版停用标点切分开关：原库已标记为弃用且不生效。保持默认即可；此项不会改变当前字幕切分。',
    'translation_backend': '翻译引擎：指定原库翻译实现，例如 NLLB、AlignAtt 或 MLX 翻译。保持当前选择；只有对应依赖、模型和运行平台齐备时才选其他实现。',
    'alignatt_url': 'AlignAtt 服务地址：填写 AlignAtt 翻译侧车的 WebSocket 地址。例：默认本机 8765 端口；只有已单独启动该服务时才需要修改。',
    'mlx_llm_mt_model': 'MLX 翻译模型：指定 MLX 翻译后端加载的模型名称或路径。保持默认模型名；仅在支持 MLX 的 Apple 芯片环境中使用该后端时修改。',
    'mlx_llm_mt_simultaneous': 'MLX 同步翻译：让 MLX 翻译尝试跟随尚未定稿的识别内容输出草稿。默认关闭；只在 MLX 翻译后端及兼容校准文件可用时开启。',
    'mlx_llm_mt_calibration': 'MLX 同步校准文件：指定同步翻译用的兼容校准参数文件。默认自动/未设置；只有有该模型对应的校准文件时填写，不能用任意文件替代。',
    'mlx_llm_mt_simul_commit': 'MLX 同步提交规则：选择何时把流式译文确认为稳定文本。默认 paper；只在同步翻译启用时调整，其他情况保留当前值。',
    'mlx_llm_mt_simul_mass_threshold': 'MLX 同步质量阈值：供 mass 提交规则判断何时确认译文。默认 0.5；仅在同步模式并选择 mass 规则时使用，保留默认除非有配套调参依据。',
    'mlx_llm_mt_simul_soft_max_s': 'MLX 同步软等待上限：控制同步译文通常等待的时间上限（秒）。默认 4 秒；仅同步翻译使用，按可接受的等待时间和配套校准调整。',
    'mlx_llm_mt_simul_hard_max_s': 'MLX 同步硬等待上限：限制同步译文等待确认的最长时间（秒）。默认 20 秒；仅同步翻译使用，通常保留默认。',
    'alignatt_preset': 'AlignAtt 配置预设：选择已定义的 AlignAtt 翻译配置。默认未指定；只有侧车服务提供相同预设时才填写。',
    'alignatt_latency': 'AlignAtt 延迟档位：选择 AlignAtt 翻译侧车使用的质量/等待配置。默认 balanced；仅 AlignAtt 后端读取，其他翻译引擎下保留不动。',
    'alignatt_context': 'AlignAtt 术语上下文：把专有词或背景信息提供给 AlignAtt 翻译侧车。例：项目名称及缩写；仅 AlignAtt 后端读取。',
    'vac': '语音活动控制：用活动检测来安排音频片段。原库默认开启；保持开启通常采用 VAC 音频分块，关闭后使用最小音频块设置。',
    'vac_chunk_size': 'VAC 分块间隔（秒）：设置 VAC 开启时送入识别流程的音频块大小。默认 0.04 秒；仅 VAC 开启时使用，通常保留默认。',
    'log_level': '日志级别：控制原库服务记录的运行细节。原库默认 DEBUG；保持默认用于当前诊断，若不需要详细记录可按运维要求降低级别。',
    'ssl_certfile': 'HTTPS 证书文件：指定服务使用的证书文件路径。默认未设置；仅部署 HTTPS 时与私钥成对配置。不要在帮助或日志中粘贴证书内容。',
    'ssl_keyfile': 'HTTPS 私钥文件：指定与证书匹配的私钥文件路径。默认未设置；仅部署 HTTPS 时配置并限制文件访问。不要粘贴或分享私钥内容。',
    'forwarded_allow_ips': '可信代理地址：限定哪些反向代理可提供转发来源信息。默认未设置；仅服务位于受信任代理之后时配置准确的代理 IP，避免信任任意来源。',
    'cors_origins': '网页跨域来源：填写允许浏览器网页访问服务的来源地址，多个值以逗号分开。默认不额外开放；只添加确实需要的网页地址。',
    'transcription': '启用语音转写：控制原库是否运行语音识别并输出文字。原库默认开启；关闭后不生成转写文本。',
    'vad': '语音活动检测：在原库识别流程中检测语音活动。默认开启；通常保持默认，只有按所选识别后端的使用说明需要时才调整。',
    'pcm_input': '原始 PCM 输入：声明输入音频采用 PCM 数据格式。原库默认关闭；仅调用端确实发送原始 PCM 时开启。桌面音频采集一般不要改动。',
    'diarization_backend': '说话人引擎：选择原库说话人分离实现。默认 Sortformer；选择 Diart 时还要准备对应模型，且需在该后端实际可用时使用。',
    'sortformer_model_path': 'Sortformer 模型路径：指定 Sortformer 说话人识别检查点。默认由原库查找；仅使用 Sortformer 且模型未放在默认位置时填写。',
    'backend_policy': '流式识别策略：选择原库 LocalAgreement 或 SimulStreaming 策略。桌面配置默认使用 LocalAgreement；按当前识别后端支持情况保留，FunASR 会强制使用 LocalAgreement。',
    'backend': '识别后端：选择原库语音识别引擎。桌面常用 faster-whisper；其他选项可能需要单独安装依赖、模型或特定硬件，只有准备好对应环境时切换。',
    'warmup_file': '预热音频文件：指定服务启动时用于预热识别引擎的音频。默认由原库准备；仅在已有合适本地短音频且需要自定义预热时填写。',
    'min_chunk_size': '最小音频块（秒）：VAC 关闭时控制音频分块的最小时长。原库默认 0.1 秒；通常保留默认，只有排查分块行为时才调整。',
    'asr_coalesce_min_s': '累计新音频阈值（秒）：累积到一定新音频后才发起下一次识别。原库默认 0 表示不启用累计阈值；通常保留默认，只有需要节制重复识别时调整。',
    'retention_seconds': '结果保留时长（秒）：限制原库在内存中保留识别结果的时长。默认自动；长会议可按内存与记录需求设置，持久化记录由桌面记录功能管理。',
    'rest_timeout': '文件转写超时（秒）：设置 REST 文件转写请求的时间预算。原库默认 0 表示自动计算；仅通过 REST 上传文件时相关。',
    'max_buffered_audio': '最大缓冲音频（秒）：限制原库排队等待处理的音频长度。默认 30 秒；通常保留默认，服务端处理跟不上输入时可按设备和接口负载检查此项。',
    'backpressure_timeout': '背压等待上限（秒）：原库等待音频队列恢复处理能力的最长时间。默认 30 秒；通常保留默认，仅在服务部署或队列排查时按需调整。',
    'model_size': '模型大小：选择当前识别后端支持的模型规格。原库默认 base，桌面可能提供已安装的 small 等值；选择前确认对应模型可用及硬件支持。',
    'model_cache_dir': '模型缓存目录：指定原库下载或读取模型缓存的位置。默认由应用配置；通常保留现有路径，只有需要迁移模型文件时更改。',
    'encoder_model_path': '编码器模型文件：指定 SimulStreaming 识别流程的编码器权重文件。默认未设置；仅该模式的模型要求拆分权重且文件已准备时填写。',
    'decoder_model_path': '解码器模型文件：指定 SimulStreaming 识别流程的解码器权重文件。默认未设置；仅该模式要求独立解码器文件且已准备时填写。',
    'lora_path': 'LoRA 适配器路径：指定与当前识别模型匹配的 LoRA 权重。默认未设置；仅在模型及所选后端明确支持该适配器时填写。',
    'direct_english_translation': 'Whisper 直接输出英文：让支持的 Whisper 后端直接生成英文结果，而不是先保留原语言文本。默认关闭；仅适用于原库支持的 Whisper 后端。',
    'buffer_trimming': '识别缓冲裁剪方式：选择 LocalAgreement 如何裁剪已处理的识别上下文。默认 segment；sentence 方式依赖语言/后端支持，保持默认除非有明确需求。',
    'confidence_validation': '置信度校验：启用 LocalAgreement 识别结果置信度检查。默认关闭；仅此流式策略使用，需有排查识别结果的理由再开启。',
    'buffer_trimming_sec': '缓冲裁剪阈值（秒）：设置 LocalAgreement 识别缓冲达到多长后考虑裁剪。原库默认 15 秒；仅 LocalAgreement 使用，通常保留默认。',
    'disable_fast_encoder': '禁用快速编码器：要求 SimulStreaming 不使用其快速编码路径。默认关闭；仅该识别策略读取，遇到编码兼容问题时才按后端说明尝试。',
    'custom_alignment_heads': '自定义对齐头：为 Whisper SimulStreaming 指定对齐头配置。默认未设置；只在模型对应的对齐配置已知并且确需覆盖内置选择时填写。',
    'frame_threshold': 'AlignAtt 帧阈值：设置 SimulStreaming 对齐策略的帧阈值。原库默认 25；仅相应策略使用，通常保留默认。',
    'beams': '解码候选数：设置支持该选项的识别后端解码时保留的候选数。原库默认 1；仅在后端确实读取时调整，增加数值可能增加工作量，通常保留默认。',
    'decoder_type': '解码器类型：指定 SimulStreaming 使用的解码方式。默认由后端选择；只在该识别模式且所用模型文档要求时填写。',
    'audio_max_len': '音频窗口上限（秒）：限制 SimulStreaming 单次处理的音频窗口长度。原库默认 30 秒；仅该模式读取，通常保留默认。',
    'audio_min_len': '音频窗口下限（秒）：设置 SimulStreaming 可处理窗口的最短音频长度。原库默认 0；仅该模式读取，通常保留默认。',
    'cif_ckpt_path': 'CIF 检查点：指定 SimulStreaming 句尾检测使用的 CIF 权重文件。默认未设置；只有适配当前模型的检查点已准备时填写。',
    'never_fire': '禁用 CIF 触发：要求 SimulStreaming 不由 CIF 检测器触发句尾提交。默认关闭；仅对该流式模式且 CIF 配置生效，通常保留默认。',
    'init_prompt': '识别初始提示：为当前识别任务提供背景或术语。默认未设置；例：会议主题、专有名称。仅在所选识别后端读取提示时生效。',
    'static_init_prompt': '固定识别提示：每次识别都复用的背景文字。默认未设置；例：常见公司缩写。仅在后端支持时生效，避免填入与会议无关内容。',
    'max_context_tokens': '最大上下文词元数：限制 SimulStreaming 识别上下文长度。默认由后端处理；仅该模式读取，只有需要控制上下文范围时按模型说明设置。',
    'segmentation_model': 'Diart 分段模型：指定 Diart 说话人分段所用模型名称或路径。默认 pyannote/segmentation-3.0；仅选择 Diart 后端时使用，并需模型可访问。',
    'embedding_model': 'Diart 声纹嵌入模型：指定 Diart 用于比较说话人声音的模型。默认 pyannote/embedding；仅选择 Diart 后端时使用。',
    'nllb_backend': 'NLLB 运行实现：选择 NLLB 模型的 Transformers 或 CTranslate2 加载路径。上游默认 Transformers；桌面可配置其他值，选择前确认该运行实现和模型已安装。',
    'nllb_size': 'NLLB 模型规格：选择 NLLB 翻译模型规格。上游默认 600M；只在 NLLB 翻译后端使用，并确认对应模型文件可用。',
    'vllm_model': 'vLLM 模型：指定 Qwen3 vLLM 识别后端加载的模型。默认未设置；仅选择 Qwen3 vLLM 后端并准备好兼容模型时填写。',
    'vllm_aligner_model': 'vLLM 对齐模型：指定 Qwen3 vLLM 流式识别使用的强制对齐模型。原库默认 Qwen3-ForcedAligner-0.6B；仅此后端使用。',
    'vllm_tensor_parallel_size': 'vLLM 张量并行数：设置 Qwen3 vLLM 模型切分使用的并行设备数量。原库默认 1；仅 vLLM 后端读取，须与可用 GPU 数量及部署方式匹配。',
    'vllm_gpu_memory_utilization': 'vLLM 显存占用目标：设置 Qwen3 vLLM 可使用的 GPU 显存比例。原库默认 0.45；仅 vLLM 后端使用，按本机其他程序占用情况谨慎调整。',
    'vllm_dtype': 'vLLM 计算精度：选择 Qwen3 vLLM 权重/计算的数据类型。原库默认 auto；仅 vLLM 后端读取，保持默认除非硬件与模型配置要求指定精度。',
    'vllm_max_model_len': 'vLLM 最大模型上下文长度：设置 Qwen3 vLLM 模型允许的上下文上限。原库默认 0 表示交由后端处理；仅 vLLM 后端使用。',
    'qwen3_vllm_audio_backend': 'Qwen3 vLLM 音频实现：选择该后端的音频编码处理路径。默认 standard；仅 Qwen3 vLLM 使用，保持默认除非所用模型/后端说明要求切换。',
    'qwen3_vllm_causal_decoder_backend': 'Qwen3 因果解码实现：选择 Qwen3 vLLM 因果文本解码器的实现。默认 vllm-text；仅该后端相关模式使用。',
    'qwen3_vllm_causal_attn_implementation': 'Qwen3 因果注意力实现：选择因果解码使用的注意力内核。默认 auto；仅 Qwen3 vLLM 因果路径使用，保持自动选择通常最稳妥。',
    'qwen3_vllm_text_decoder_model': 'Qwen3 文本解码模型：指定独立文本解码器模型。默认未设置；仅所用 Qwen3 vLLM 架构需要单独文本解码器时填写。',
    'qwen3_vllm_live_idle_timeout_ms': 'Qwen3 实时空闲等待（毫秒）：设置该后端实时处理空闲时等待新音频的间隔。默认 50 毫秒；仅 Qwen3 vLLM 实时识别使用，通常保留默认。',
    'qwen3_vllm_tower_checkpoint': 'Qwen3 音频塔权重：指定 Qwen3 vLLM 音频编码塔检查点路径。默认未指定；仅使用该后端且权重不在默认位置时填写。',
    'qwen3_vllm_left_context_sec': 'Qwen3 左侧音频上下文（秒）：设置 Qwen3 vLLM 每次识别可参考的前段音频范围。默认 15 秒；仅该后端使用，通常保留默认。',
    'qwen3_vllm_block_frames': 'Qwen3 音频帧块大小：设置 Qwen3 vLLM 处理的音频帧块长度。默认 192；仅该后端使用，保持默认除非有兼容配置依据。',
    'qwen3_vllm_cache_block_size': 'Qwen3 KV 缓存块大小：设置 Qwen3 vLLM 缓存分块参数。默认 0 表示后端默认；仅 Qwen3 vLLM 使用，通常保留默认。',
    'qwen3_vllm_segment_max_steps': 'Qwen3 单段最大步数：限制 Qwen3 vLLM 一段识别最多执行的解码步数。默认 150；仅该后端使用，保持默认除非按模型说明调整。',
    'qwen3_vllm_segment_min_sec': 'Qwen3 最短识别片段（秒）：设置该后端开始一段识别所需的最短时长。默认 0；仅 Qwen3 vLLM 使用，通常保留默认。',
    'qwen3_vllm_prompt_context_words': 'Qwen3 提示上下文词数：控制该后端从已有文字中带入多少词作为下一段提示。默认 0；仅 Qwen3 vLLM 使用，需要上下文提示时再设定。',
    'qwen3_vllm_live_multiprocessing': 'Qwen3 实时多进程：控制 Qwen3 vLLM 实时路径是否使用多进程。默认自动；仅该后端使用，保留自动除非部署排查要求明确指定。',
    'qwen3_vllm_aligner_multiprocessing': 'Qwen3 对齐器多进程：控制 Qwen3 vLLM 对齐器是否使用多进程。默认自动；仅该后端使用，保留自动除非部署排查要求明确指定。',
    'holdback_words': '末尾暂缓词数：在流式结果中暂不确认末尾若干词，以减少后续修订影响。默认自动；仅读取此通用选项的流式后端使用。',
    'trim_sentence_buffer': '裁剪句子缓冲：控制是否按句子边界整理识别缓冲。默认开启；仅支持此选项的流式后端使用，通常保留默认。',
    'qwen3_vllm_metal_audio_backend': 'Qwen3 Metal 音频实现：选择 MLX/Metal 版本 Qwen3 vLLM 的音频处理路径。默认 standard；仅对应 Metal 后端使用，其他后端忽略。',
    'qwen3_vllm_metal_tower_checkpoint': 'Qwen3 Metal 音频塔权重：指定 Metal 后端音频编码塔检查点路径。默认未指定；仅该后端且模型不在默认位置时填写。',
    'qwen3_vllm_metal_left_context_sec': 'Qwen3 Metal 左侧上下文（秒）：设置 Metal 后端参考的前段音频范围。默认 15 秒；仅对应 Metal 后端读取，通常保留默认。',
    'qwen3_vllm_metal_block_frames': 'Qwen3 Metal 音频帧块大小：设置 Metal 后端处理音频的帧块长度。默认 192；仅对应后端读取，通常保留默认。',
    'qwen3_streaming_chunk_sec': 'Qwen3 流式音频块（秒）：设置 Qwen3 Streaming 每个新音频窗口的长度。原库默认 2 秒；仅此后端使用，通常保留默认。',
    'qwen3_streaming_left_context_sec': 'Qwen3 流式左上下文（秒）：设置新窗口重用的历史音频范围。默认 12 秒；仅 Qwen3 Streaming 使用，通常保留默认。',
    'qwen3_streaming_right_context_ms': 'Qwen3 流式右上下文（毫秒）：设置窗口前瞻音频时长。默认 640 毫秒；仅 Qwen3 Streaming 使用，按该模型配置保留默认。',
    'qwen3_streaming_segment_max_steps': 'Qwen3 流式单段最大步数：限制每个识别段的最大生成步数。默认 200；仅 Qwen3 Streaming 使用。',
    'qwen3_streaming_segment_keep_tail_steps': 'Qwen3 流式保留尾部步数：设置分段间保留的尾部生成步数。默认 0；仅 Qwen3 Streaming 使用，通常保留默认。',
    'qwen3_streaming_hold_back_words': 'Qwen3 流式暂缓词数：暂不确认识别结果末尾的词数。默认 6；仅 Qwen3 Streaming 使用，通常保留默认。',
    'qwen3_streaming_stable_iterations': 'Qwen3 稳定轮数：指定多少次窗口结果一致后确认文本。默认自动（原库按窗口/因果模式处理）；仅 Qwen3 Streaming 使用。',
    'qwen3_streaming_max_new_tokens': 'Qwen3 最大新词元数：限制单次识别生成的 token 数量。默认 256；仅 Qwen3 Streaming 使用，过小可能截断输出，通常保留默认。',
    'qwen3_streaming_device': 'Qwen3 运行设备：指定 Qwen3 Streaming 模型使用的设备。默认 auto；仅此后端使用，只有设备环境明确要求时才覆盖自动选择。',
    'qwen3_streaming_dtype': 'Qwen3 计算精度：设置 Qwen3 Streaming 模型的数值类型。默认 auto；仅此后端使用，保持自动除非模型/设备要求指定。',
    'qwen3_streaming_attn_implementation': 'Qwen3 注意力实现：指定 Streaming 后端使用的注意力实现。默认 auto；仅 Qwen3 Streaming 使用，通常保留自动。',
    'qwen3_streaming_context': 'Qwen3 识别上下文：为 Qwen3 Streaming 提供背景或词汇提示。默认空；例：会议主题或专有名称，仅此后端读取。',
    'qwen3_streaming_prompt_context_words': 'Qwen3 提示上下文词数：从已有转写中选取多少词作为后续提示。默认 0；仅 Qwen3 Streaming 使用，需上下文续接时再设定。',
    'qwen3_streaming_audio_backend': 'Qwen3 Streaming 音频路径：选择该后端的音频编码处理方式。默认 windowed；仅 Qwen3 Streaming 读取，通常保留默认。',
    'qwen3_streaming_tower_checkpoint': 'Qwen3 Streaming 音频塔权重：指定该后端使用的音频编码塔检查点。默认未指定；仅 Qwen3 Streaming 且权重需手动定位时填写。',
    'qwen3_streaming_block_frames': 'Qwen3 Streaming 帧块大小：设置音频塔处理的帧块长度。默认 192；仅该后端使用，通常保留默认。',
    'canary_model': 'Canary 识别模型：指定 NeMo Canary 后端加载的模型。原库默认 nvidia/canary-1b-v2；仅选择 Canary 后端时使用，需模型可访问。',
    'canary_default_lang': 'Canary 默认语言：设置 Canary 后端在语言未指定或需回退时使用的语言代码。原库默认 en；仅 Canary 后端使用。',
    'canary_lid_model': 'Canary 语言识别模型：为 Canary 后端指定语言检测模型。默认 langid_ambernet；仅启用 Canary 识别且使用语言检测时相关。',
    'canary_lid_min_sec': 'Canary 语言检测最短音频（秒）：设置至少累积多少音频再判断语言。原库默认 2 秒；仅 Canary 后端使用，通常保留默认。',
    'canary_lid_min_conf': 'Canary 语言检测最低置信度：设置采用检测语言所需的置信度阈值。原库默认 0.5；仅 Canary 后端使用，需有语言检测排查依据再调整。',
    'pause_segmentation_seconds': '停顿断句（秒）：讲话停顿超过此时长后形成稳定句子边界。桌面当前默认可能由应用设为 0.8 秒；仅非负数有效，保留当前值除非想改变断句等待。',
    'sortformer_max_speakers': 'Sortformer 人数上限：限制 Sortformer 输出的说话人通道数，允许 1–4。默认未设置表示使用检查点提供的通道；仅 Sortformer 后端使用。',
}


def help_for(key: str, fallback: str = "") -> str:
    key = str(key or "")
    if key in HELP_TEXT:
        return HELP_TEXT[key]
    return str(fallback or f"WhisperLiveKit 参数 {key}：请保留当前值；该项仅在对应识别/翻译后端读取。")
